version: '3.7'
services:
    web:
        build: .
        command: bash -c "gunicorn app:app --name pillar_homework --bind 0.0.0.0:5000 --workers 1 --log-level=info --log-file=/logs/gunicorn.log --access-logfile=/logs/gunicorn-access.log"
        environment:
            - APP_SETTINGS=config.DevelopmentConfig
        volumes:
            - ./logs:/logs
        networks:
            - web_nw
    nginx:
        image: "nginx:mainline-alpine"
        ports:
            - "80:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./web/app/build:/usr/share/nginx/html:ro
        depends_on:
            - web
        networks:
            - web_nw
networks:
    web_nw:
        driver: bridge
